spring.jpa.open-in-view=false
spring.profiles.active=dev-test


app.jwt.secret=change-this-secret-to-at-least-256-bits-before-production
app.jwt.access-token-expiration-seconds=600

app.jwt.refresh-token-expiration-seconds=86400

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huynhtienloc6002@gmail.com
spring.mail.password=eutf qint miot ixrj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
