spring.datasource.url=jdbc:mysql://localhost:3306/rikkei_banking_devTest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=loc123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.h2.console.enabled=true

app.seed.dev-test.enabled=true
